config/routes.rb
Rails.application.routes.draw do
  resources :pee_pees

  root :to => "pee_pees#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pee_pee.rb
class PeePee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pee_pees_controller.rb
class PeePeesController < ApplicationController
  before_action :set_pee_pee, only: [:show, :edit, :update, :destroy]

  # GET /pee_pees
  # GET /pee_pees.json
  def index
    @pee_pees = PeePee.all
    @pee_pee = PeePee.new
  end

  # GET /pee_pees/1
  # GET /pee_pees/1.json
  def show
  end

  # GET /pee_pees/new
  def new
    @pee_pee = PeePee.new
  end

  # GET /pee_pees/1/edit
  def edit
  end

  # POST /pee_pees
  # POST /pee_pees.json
  def create
    @pee_pee = PeePee.new(pee_pee_params)

    respond_to do |format|
      if @pee_pee.save
        format.html { redirect_to root_url, notice: 'Pee pee was successfully created.' }
        format.json { render :show, status: :created, location: @pee_pee }
      else
        format.html { render :new }
        format.json { render json: @pee_pee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pee_pees/1
  # PATCH/PUT /pee_pees/1.json
  def update
    respond_to do |format|
      if @pee_pee.update(pee_pee_params)
        format.html { redirect_to @pee_pee, notice: 'Pee pee was successfully updated.' }
        format.json { render :show, status: :ok, location: @pee_pee }
      else
        format.html { render :edit }
        format.json { render json: @pee_pee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pee_pees/1
  # DELETE /pee_pees/1.json
  def destroy
    @pee_pee.destroy
    respond_to do |format|
      format.html { redirect_to pee_pees_url, notice: 'Pee pee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pee_pee
      @pee_pee = PeePee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pee_pee_params
      params.require(:pee_pee).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pee_pees_helper.rb
module PeePeesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shepeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pee_pees/_form.html.erb
<div class="center jumbotron">
  <%= form_with(model: pee_pee, local: true) do |form| %>
    <% if pee_pee.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pee_pee.errors.count, "error") %> prohibited this pee_pee from being saved:</h2>

        <ul>
        <% pee_pee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.hidden_field :description, id: :pee_pee_description %>
    </div>

    <div class="actions">
      <%= form.submit "SHE PEED!", class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>

app/views/pee_pees/edit.html.erb
<h1>Editing Pee Pee</h1>

<%= render 'form', pee_pee: @pee_pee %>

<%= link_to 'Show', @pee_pee %> |
<%= link_to 'Back', pee_pees_path %>

app/views/pee_pees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="center jumbotron">
  <h1>Record a Pee</h1>
  <%= render 'form', pee_pee: @pee_pee %>
  <h2>Boubs last peed <strong><%= ((Time.now - PeePee.last.created_at) / 1.hour).round(1) %></strong> hours ago</h2>
</div>
<table>
  <thead>
    <tr>
      <th>List of pee pees</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pee_pees.order("created_at desc").each do |pee_pee| %>
      <tr>
        <td><%= pee_pee.created_at.strftime('%A')%> @ <%= pee_pee.created_at.strftime('%r')%></td>
        <td><%= button_to 'Delete', pee_pee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pee_pees/new.html.erb
<h1>New Pee Pee</h1>

<%= render 'form', pee_pee: @pee_pee %>

<table>
  <thead>
    <tr>
      <th>List of pee pees</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pee_pees.each do |pee_pee| %>
      <tr>
        <td><%= pee_pee.created_at.strftime('%A')%> @ <%= pee_pee.created_at.strftime('%r')%></td>
        <td><%= button_to 'Delete', pee_pee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pee_pees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pee_pee.description %>
</p>

<%= link_to 'Edit', edit_pee_pee_path(@pee_pee) %> |
<%= link_to 'Back', pee_pees_path %>